version: "2"

volumes:
  orderer.istc.com:
  peer0.istcorg1.istc.com:

networks:
  istc_network:

services:

  orderer.istc.com:
    container_name: orderer.istc.com
    image: hyperledger/fabric-orderer:2.3.0
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../istc-genesis-block/istcGenesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../ca-configurations/istc/ordererOrganizations/istc.com/orderers/orderer.istc.com/msp:/var/hyperledger/orderer/msp
      - ../ca-configurations/istc/ordererOrganizations/istc.com/orderers/orderer.istc.com/tls/:/var/hyperledger/orderer/tls
      - orderer.istc.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - istc_network

  peer0.istcorg1.istc.com:
    container_name: peer0.istcorg1.istc.com
    image: hyperledger/fabric-peer:2.3.0
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_istc_network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.istcorg1.istc.com
      - CORE_PEER_ADDRESS=peer0.istcorg1.istc.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.istcorg1.istc.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.istcorg1.istc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.istcorg1.istc.com:7051
      - CORE_PEER_LOCALMSPID=ISTCOrg1MSP
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../ca-configurations/istc/peerOrganizations/istcorg1.istc.com/peers/peer0.istcorg1.istc.com/msp:/etc/hyperledger/fabric/msp
      - ../ca-configurations/istc/peerOrganizations/istcorg1.istc.com/peers/peer0.istcorg1.istc.com/tls:/etc/hyperledger/fabric/tls
      - peer0.istcorg1.istc.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
    networks:
      - istc_network

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.3.0
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ../ca-configurations/istc:/opt/gopath/src/github.com/hyperledger/fabric/peer/ca-configurations/istc
      - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.istcorg1.istc.com
    networks:
      - istc_network
